apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJpbHlhMDkyMyIsInBhc3N3b3JkIjoiRVE4LXJkcC1NQ1ktc0g1IiwiYXV0aCI6ImFXeDVZVEE1TWpNNlJWRTRMWEprY0MxTlExa3RjMGcxIn19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: docker-registry-secret
  namespace: echo-app
type: kubernetes.io/dockerconfigjson
