replicaCount: 3

image: 
  repository: ilya0923/echo-server-python
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: docker-registry-secret

env: 
  AUTHOR: "Ilya Sulimenko"

service: 
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  host: echo-app.cloud.ru
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /